### ISSUE TITLE
Change syntax for links to assignments

### ISSUE THREAD

**Issue by seetee** [klovaaxel/schedule#24]
Today a link to an assignment is formatted as follows: 

`[Uppgift: Min Fula Lilla Sida](https://tcstenungsund.github.io/schedule/assignment.html?link=assignments/weuweb01-min_fula_lilla_sida "Min Fula Lilla Sida")`

My suggestion is to change the syntax to this: 

`[Min Fula Lilla Sida](assignments/weuweb01-min_fula_lilla_sida.md "Min Fula Lilla Sida")`

Let JavaScript identify that the link starts with "assignment", remove the .md and add the rest of the URL. 

This will enable navigating from schedule to assignment in the original markdown documents on GitHub. It will also keep the links working when the repository is frozen in a release at the end of every academic year.

**Comment by klovaaxel** [comment]
The keyword "Uppgift" or similar would still be needed for assignments that point to external resources so I'm skeptical about using the URL for that. Will look into formatting the URL to support "local" navigation on github
