### ISSUE TITLE
Change lunch text in dark mode

### ISSUE THREAD

**Issue by pontalainen** [klovaaxel/schedule#26]
The text in the lunch view currently seems to have no support for dark mode, with not so good contrasts.
 
![Skärmavbild 2023-08-28 kl  09 32 39](https://github.com/klovaaxel/schedule/assets/58231866/3d3b408b-7aa6-4171-bbbb-2e4c1ec4dbcc)

**Comment by klovaaxel** [comment]
This is essentially a limitation of skolmaten.se as this is just an embedded view of their website. But the new schedule branch (dev-schedule-3-0) now has a "fix" where the background is kept white even when in dark mode.
