### ISSUE TITLE
Some code are treated as code blocks

### ISSUE THREAD

**Issue by seetee** [klovaaxel/schedule#34]
Some code that are used to generate the assignments are treated as code blocks and part of the assignment. 

![image](https://github.com/klovaaxel/schedule/assets/5168530/2ce20755-b4f9-4fb6-9629-cc4394e136d0)

**Comment by klovaaxel** [comment]
Hmm, that's kinda weird... It seems like I'm not adding .md to the end of the URL if it is missing but apparently going to this URL "https://tcstenungsund.github.io/schedule/md/assignments/weuweb01-min_fula_lilla_sida" results in a webview of the markdown document... It must be a GitHub pages thing.

**Comment by seetee** [comment]
Ah, right. Then I have a workaround, great!
